### ISSUE TITLE
Missing dependency to `stringr`?

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#1]
The message `'regex' is not an exported object from 'namespace:stringr'` appears when calling `rt` in the console. Is a dependency to `stringr` missing?

**Comment by surmann** [comment]
Talked to Michel, nobody knows why the dependency from `docopt` to `stringr` is not installed.

**Comment by surmann** [comment]
After the update to R-3.3.1 x64, I try to install `rt`. I get the two missing dependencies to `backports` and `chron`. After calling `rt` from the PowerShell (yes, I use Windows) the `stringr` is missing.
Does it make sense to add these three packages to the dependencies?

**Comment by berndbischl** [comment]
not really, as the package uses stringi for string ops.

can you see what exactly triggers the stringr problem? i greped for stringr in the code base and cannot find it. also r cmd check should pick this up?

**Comment by surmann** [comment]
Good question. I get the message "there is no package called 'stringr'" when I call `rupdate` from the command prompt. The corresponding call from inside `R` works properly.

Should we rank these problems as Windows related?
Currently, I add them to the `package` file and `rt` installs them.

**Comment by berndbischl** [comment]
i dont think this is a windows issue.
(but just guessing)

 but i have no idea where stringr should be needed. if you find this, it would be simple to convert the class into stringi calls and resolve this. 


sorry

adding string to DEPENDS without knowing WHY is really not a good option....

**Comment by surmann** [comment]
Do you have a hint how to find out where `stringr` is used, because I get the message "there is no package called 'stringr'" only in the console.

**Comment by surmann** [comment]
Here we are!
`roxygen2` depends on `stringr`.

I don`t know why, but dependencies are sometimes not installed correctly.
