### ISSUE TITLE
functions like rinstall and rcheck do not call roxygenize

### ISSUE THREAD

**Issue by berndbischl** [rdatsci/rt#14]
at least the NAMESPACE is therefore not correctly written before the next operation

**Comment by mllg** [comment]
`rcheck` now rebuilds the documentation if the "roxygennote" field is found in the description.

`rinstall` is intended to install remote packages, here I definitely do not want to call roxygen.

**Comment by mllg** [comment]
(`rinstall` for a local package does now also document ...)

**Comment by berndbischl** [comment]
Ok thx. I was also getting confused because of your choice of names....

I KNOW that rmake installs the package, but in my head rmake always implies "build it", weil "rinstall" well implies "install it" (for a local package)

So I catch myself very often typing "rinstall ."....
