### ISSUE TITLE
it is really hard to install rt

### ISSUE THREAD

**Issue by berndbischl** [rdatsci/rt#15]
First, I got a stringr error:

'regex' is not an exported object from 'namespace:stringr' 

Forcing me to update this. So at least the version dep in not correctly set in rt:DESCRIPTION.

After a stringr update I now get this:

di68kay@lxa191:~/cos/BatchJobs> rmake
Error: unused argument (create = FALSE)

Which does not even tell me the function/package it relates to. I had this before, now I have to search again which package I have to update :(

**Comment by berndbischl** [comment]
I guess it is devtools, where the version dep is again also wrong

**Comment by mllg** [comment]
You have to debug it yourself, this is not reproducible.

**Comment by berndbischl** [comment]
I already told you the answer, depend on the recent versions?

and put it on cran

**Comment by berndbischl** [comment]
i also told you which stuff in the signatures you need, if you want to depend on older versions....

**Comment by berndbischl** [comment]
and guess how i found those answers.... by debugging it myself

**Comment by mllg** [comment]
Send a PR then.

**Comment by berndbischl** [comment]
i have depended on the newest devtools version, which implies R 3.0.2

do you use stringr internally? I guess you cannot, as only stringi is in rt NS?

so I might guess that the stringr problem is actually due to devtools as well

why not push to cran?

**Comment by mllg** [comment]
> do you use stringr internally? I guess you cannot, as only stringi is in rt NS?

Exactly. I only use `stringi`.

> so I might guess that the stringr problem is actually due to devtools as well

So, still broken?

> why not push to cran?

I will, as soon as I think that rt is mature enough. But this would not fix this issue, you obviously got `rt` installed, right?

**Comment by berndbischl** [comment]
> So, still broken?

I dont get your point? Also, I cannot check this, I would need to go back in installed versions of dependencies on my system.

> you obviously got rt installed, right?

I did yes. Most other people would have not. It also cost me more lifetime then it should.

Also: 

if we use it all the time why is it not mature enough?

**Comment by berndbischl** [comment]
The more underlying question is also, how can one check if the version requirements one put into DESCRIPTION are actually correct.

I guess there is no doable approach though. This would require downloading outdated versions from CRAN (which cannot be automated).

My final suggestions here:

a) close this issue
b) upload to CRAN
