### ISSUE TITLE
rknit? 

### ISSUE THREAD

**Issue by berndbischl** [rdatsci/rt#20]
i guess we have rmakrdown now.

would we also like to hve support for knitr? 
not needed?

it would love to do that from the console

**Comment by surmann** [comment]
Take a look at ea0c0be. Does this work for you?

**Comment by surmann** [comment]
Both `rmarkdown` and `rknit` were available in `rcompile`, weren`t they?

**Comment by surmann** [comment]
We have to manually compile a `.bib` file with `rknit`. It only updates and compiles the `.tex` file.

**Comment by surmann** [comment]
I updated `rknit`, `rmarkdown`, and `rcompile` with 2d3aa99.
