### ISSUE TITLE
Again, it is not OK that the dir where the check logs are stored is removed after rcheck

### ISSUE THREAD

**Issue by berndbischl** [rdatsci/rt#3]
I need to read them in cases of error

**Comment by jakobbossek** [comment]
+1

**Comment by mllg** [comment]
Does the argument `--nocleanup` work for you guys?

`rcheck --help`

**Comment by berndbischl** [comment]
No, because it is not the default.

**Comment by berndbischl** [comment]
I can see why one does not want these files filling up the project dir, but why not put them in the temp, and leave them there, and print out the path to the logfiles?

**Comment by berndbischl** [comment]
(Which is exaxtly what happens now, minus the "leaving the directory, instead of removing it")

**Comment by mllg** [comment]
The temp directory should not be removed with `--nocleanup`?

**Comment by berndbischl** [comment]
You are not answering to what I said?

**Comment by mllg** [comment]
The temp directory is already persistent if you pass the argument.

If you do not like the default, you can always toggle it by defining a bash alias.

Reason to not make `nocleanup` the default: `/tmp` is nowadays usually mounted as tmpfs. If you do not clean up, you might end up using a considerable amount of memory on systems with longer uptimes (e.g., compute servers).

**Comment by berndbischl** [comment]
Ok, thanks for the info in the last reply at the end.

What happens is that people get confused here:
```
Status: 1 ERROR
See
  ‘/tmp/RtmpiAht3F/BBmisc.Rcheck/00check.log’
for details.
```

And then that dir does not exist. I would at least point them to the "nocleanup" option in a helpful info message.

**Comment by berndbischl** [comment]
Preferrably at the end of the output.

**Comment by surmann** [comment]
An info in case of the default would be fine.
