### ISSUE TITLE
Error with rupdate

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#34]
I get the following error with `rupdate` on Windows 10:
    
    Error: (converted from warning) cannot open compressed file '//C:%5CUsers%5CName%5CAppData%5CLocal%5CR-crancache%5CR-crancache%5CCache/cran/src/contrib/PACKAGES', probable reason 'Invalid argument'

Any ideas?

**Comment by mllg** [comment]
https://github.com/r-lib/crancache/issues/28

**Comment by surmann** [comment]
Seems to work.
