### ISSUE TITLE
rupdate broken?

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#46]
Today I got the following message:

    > rupdate
    Checking for outdated packages ...
    Error: values must be length 1,
     but FUN(X[[1]]) result is length 0

Is there any work ongoing which temporary causes this issue?

**Comment by jakob-r** [comment]
Probably I broke something... I will check

**Comment by surmann** [comment]
Here is my `traceback()`:

    > traceback()
    4: vapply(li, "[[", what, FUN.VALUE = NA_character_) at helper.r#31
    3: extract(pkgs, "type")
    2: factor(extract(pkgs, "type")) at rupdate.r#28
    1: rupdate()

You get my `package` file in a minute.

**Comment by jakob-r** [comment]
Should work again. Have to find a way to test it nicely though.

**Comment by surmann** [comment]
Seems to work.
