### ISSUE TITLE
rspell update to hunspell

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#52]
I like the more compact output of hunspell. Should we update `rspell` to `hunspell`?

**Comment by surmann** [comment]
In the meantime I found the package `spelling`: https://github.com/ropensci/spelling

What do you think? It checks the whole package, also as unit tests, and runs smoothly under windows.

If you have no concerns, I would like to change the spell check to `spelling::spell_check_package()`.

**Comment by mllg** [comment]
Ok for me.

**Comment by jakob-r** [comment]
@surmann Do you want to do the PR?

**Comment by surmann** [comment]
Yes. I just want to know if you have any thoughts on this or if it is ok for you.

**Comment by surmann** [comment]
@jakob-r Do you have any ideas why Appveyor fails on this commit?

**Comment by jakob-r** [comment]
Sorry. I don't have a clue. I guess it runs through on Windows locally?

**Comment by surmann** [comment]
Yes. I tested and checked it on my machine.
Should we merge the commit?

**Comment by jakob-r** [comment]
done :)
