### ISSUE TITLE
Missing dependency stops rupdate

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#55]
`graph` package is currently not available on CRAN, but `rupdate` wants to install this dependency to another package on my machine. My problem is, this unavailable package stops the whole update process:

    > rupdate                                                          
    Checking for outdated packages ...                                 
    Auto update packages...                                            
    dplyr    (0.7.8 -> 0.8.0.1) [CRAN]                                 
    ellipsis (NA    -> 0.0.2  ) [CRAN]                                 
    forcats  (0.3.0 -> 0.4.0  ) [CRAN]                                 
    igraph   (1.2.3 -> 1.2.4  ) [CRAN]                                 
    readxl   (1.2.0 -> 1.3.0  ) [CRAN]                                 
    Skipping 1 packages not available: translations                    
    Installing 5 packages: dplyr, ellipsis, forcats, igraph, readxl    
    Installing packages into 'C:/Users/.../Documents/RPackages'       
    (as 'lib' is unspecified)                                          
    Error: (converted from warning) dependency 'graph' is not available

Is it possible to skip those packages with a warning at the end and continue with the rest of the packages?

P.S.: Because I don't know which packages causes this error, I delete all packages and started from the scratch last week. Unfortunately, I have the same error this week again.

**Comment by jakob-r** [comment]
The problem was that rupdate was told to also install the suggests which does not seem to be a good idea. I changed that and now only dependencies and imports (and LinkingTo) are installed if needed.
Additionally there is now a safemode which tries to update each package on it's own and collects all fails and prints them in the end. Can you try it out?

**Comment by surmann** [comment]
It runs now smoothly without the option but good to have this option. I will try it, when I observe such a problem again.
