### ISSUE TITLE
Quick installation of git packages

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#7]
I add the flag `--noquick` in commit 5dda85ddb52162a8bda697afa59e1c0f9059bde6 to install git packages on all architectures.

Should we switch the installation behaviour to be not quick on default? The option `--quick` will use the fast installation from `devtools`.
This will correspond to the standard behaviour from `devtools` and I myself assumed a default installation on all architectures.

**Comment by surmann** [comment]
I have to emphasise this question. `rupdate` uses the internal `installPackage` function which standard settings is a quick install. Hence, new packages are only installed on standard architecture which causes an error on e.g. `R CMD check`.

**Comment by mllg** [comment]
Please give me a little more information: On what kind of systems does `devtools::install()` fail to build the package, and why? Can this possibly be fixed upstream?

**Comment by surmann** [comment]
I use the 64-bit version of R on my Windows system by default. Hence, an `rinstall` of a git package only compiles the sources to R-64 bit.
Now I do a `R cmd check` of another package and this is done on R 32 bit and 64 bit. This check fails obviously, because of the missing installation on R 32 bit.

Does this fills the gap?

**Comment by surmann** [comment]
From the devtools help:
```
quick:
if TRUE skips docs, multiple-architectures, demos, and vignettes, to make installation as fast as possible.
```

What do you think, should I change the code to the default "noquick" and change the option to `--quick`?

**Comment by surmann** [comment]
It remains as it is.
