### ISSUE TITLE
rupdate of Rcpp

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#8]
If `rupdate` has to update the package `Rcpp` I get the following error on my evil Windows machine:

```
package 'Rcpp' successfully unpacked and MD5 sums checked
Warnung: cannot remove prior installation of package 'Rcpp'
```

After that `rt` cannot be loaded when I start `R`.

Does anyone know the reason for this issue and how to solve it?

**Comment by jakobbossek** [comment]
`remove.packages('Rcpp')` should help. However, it wuld be interesting to know why this error occurs. I mean, why the prior installation cannot be removed. Maybe you have only restricted rights for the package install directory?

**Comment by surmann** [comment]
I can remove the package, even not being an admin. However, than `rupdate` is not possible any more, because on import of `rt` depends on `Rcpp`.
