### ISSUE TITLE
new function: rtstchk

### ISSUE THREAD

**Issue by surmann** [rdatsci/rt#9]
Currently, `rcheck` aka `devtools::check` does not run the unit tests. They are only run by `rtest` aka `devtools::test`.
Should we implement a function `rtstchk` which runs the unit test first and than the R CMD check?

**Comment by jakob-r** [comment]
:+1: +1

**Comment by berndbischl** [comment]
To be honest, I find it quite nice that the 2 are separate. But I also see no hurt in adding a separate command. Do a PR?

**Comment by surmann** [comment]
It is ok. But you have to know it.
I discovered it while developing `ecr`. Yesterday it was a new info for some colleagues. If you assume `rcheck` do the tests, you can run into problems.

If you guys think it is helpful I implement the function.

**Comment by surmann** [comment]
Done in commit 28abf6616963c7d590af1d8e9995c10ec08f8172
